Use a different set of commands to detect fourslash test updates (microsoft/typescript-go#1923)

diff --git a/tsc/.github/workflows/ci.yml b/tsc/.github/workflows/ci.yml
--- a/tsc/.github/workflows/ci.yml
+++ b/tsc/.github/workflows/ci.yml
@@ -243,7 +243,16 @@ jobs:
       - run: node --experimental-strip-types ./internal/lsp/lsproto/_generate/generate.mts
 
       - name: Regenerate fourslash tests and update failing test list
-        run: npm run updatefailing
+        run: |
+          echo "" > ./internal/fourslash/_scripts/failingTests.txt
+          npm run convertfourslash || true
+          npx hereby test || true
+          npx hereby baseline-accept || true
+          npm run updatefailing || true
+          npx hereby baseline-accept || true
+          rm -rf testdata/baselines/reference/fourslash || true
+          npx hereby test || true
+          npx hereby baseline-accept || true
 
       - run: git add .
       - run: git diff --staged --exit-code --stat
